version: "3.9"
services:
  server:
    image: ghcr.io/scoutingscherpenzeel/jotihunt-tracker-server:latest
    restart: unless-stopped
    environment:
      - DEBUG=false
      - JWT_SECRET=
      - MONGO_URI=mongodb://mongodb:27017/jotihunt
      - TRACCARR_API_URL=
      - TRACCARR_API_TOKEN=
      - JOTIHUNT_API_URL=https://jotihunt.nl/api/2.0
      - JOTIHUNT_WEB_URL=https://jotihunt.nl
      - JOTIHUNT_WEB_USERNAME=
      - JOTIHUNT_WEB_PASSWORD=
      - HUNT_START_DATE=
      - HUNT_END_DATE=
    ports:
      - "3000:3000"
  client:
    image: ghcr.io/scoutingscherpenzeel/jotihunt-tracker-client:latest
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - API_BASE_URL=
      - MAPBOX_TOKEN=
      - HUNT_START_TIME=
      - HUNT_END_TIME=
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=jotihunt
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb:
