version: "3.9"
services:
  server:
    image: ghcr.io/scoutingscherpenzeel/jotihunt-tracker-server:latest # of ":main" voor de laatste ontwikkelversie.
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
  client:
    image: ghcr.io/scoutingscherpenzeel/jotihunt-tracker-client:latest
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mongodb:/data/db
  traccar:
    image: traccar/traccar:ubuntu
    restart: unless-stopped
    ports:
      - 5055:5055 # UDP poort voor GPS trackers
      - 8082:8082 # Webinterface en API
    volumes:
      - traccar_logs:/opt/traccar/logs
      - traccar_data:/opt/traccar/data
      - traccar_conf:/opt/traccar/conf

volumes:
  mongodb:
  traccar_logs:
  traccar_data:
  traccar_conf: